### PR TITLE
Explicit sleep management

### PR DESCRIPTION
**Pull request by nullpainter**
This PR implements explicit sleep management, as per #23.

Sleep management is required because MAME ignores both screen and PC sleep settings. With this PR, the user's screens are turned off and MAME stopped based on the user's sleep settings. This makes Mamesaver a better citizen, is more environmentally friendly, and stops unnecessarily and constantly high CPU usage if the screensaver is left on overnight.

This change:

1. Reads the user's preferences for putting the screen and PC to sleep
2. Identifies the current power source
3. Listens for power source change events
4. Stops MAME and sleeps monitors when either screen or PC sleep times are reached

Note that no power actions other than sleeping screens is performed (i.e., we are treating requests to hibernate etc. as if it was a screen sleep event).

### CODE REVIEW

**Comment by mika76** [comment]
I've merged the hotkeys one so I'm not sure if you need to merge here?

**Comment by mika76** [comment]
Hey @nullpainter I merged the multi screen PR and it seems to have some conflicts here - sorry about that...

**Comment by nullpainter** [comment]
No worries, @mika76. All done.

**Comment by mika76** [comment]
Nice - I'll merge it quick 😉

**Pull request merged**
