### PR TITLE
Multiscreen enhancements

### PR DESCRIPTION
**Pull request by andyvans**
Hi Mika. Here are some changes to allow the primary Mame monitor to be picked. The selection is either 'Highest Resolution' or 'Windows Primary'.  This is handy for where there are high DPI monitors or you prefer the Primary monitor to host Mame.

### CODE REVIEW

**Comment by mika76** [comment]
Hey @andyvans great thanks! I've been so busy with work and rl that I totally forgot to make a release for v3 - I guess this could go in too, I just have to fix up the installer...

**Comment by nullpainter** [comment]
You'll note I've been too polite to mention it 😉

**Comment by mika76** [comment]
> You'll note I've been too polite to mention it 😉

Hehe noted. I hang my head in shame...

**Comment by mika76** [comment]
@andyvans so the dropdown only ever has those choices (highest res or primary) or does it get the list of screen? Just trying to understand how it works...

**Comment by andyvans** [comment]
@mika76 It only has those two choices. It doesn't detect and list monitors that you may have. The purpose is to choose the screen on which MAME with run on. 

If streaming to other monitors is enabled then this decides the source of the stream.  On some games the streamed/cloned screens can have visual defects so choosing your primary or highest resolution can reduce the amount it bothers you (depending on which one you mainly look at)

**Comment by mika76** [comment]
Merged, updated, and all sorted now. 😌 

btw come join us on https://gitter.im/mika76/mamesaver @andyvans ...

**Pull request merged**
