### PR TITLE
Bug fixes for game list parsing

### LINKED ISSUE #35: Generic error message if ROM path not found
If an invalid ROM path is present in `mame.ini`, a generic dialog is displayed indicating that the path to MAME is incorrect. This should be changed to display the offending path in question.

### PR DESCRIPTION
**Pull request by nullpainter**
The primary fix for this PR is #34, however also fixes #35 and #36.

The output of `mame64.exe -showconfig` for a file path line results in the paths containing speech marks if:

- They are enclosed in speechmarks in `mame.ini`; or
- They contain spaces

For example, both of these examples result in speech marks:

- `rompath  roms;c:\my stuff\roms`
`rompath  "roms;c:\my stuff\roms"`

Note that the hybrid (and invalid) config line `rompath   roms;"c:\my stuff\roms"` is parsed by MAME, but the quoted value is silently ignored.

I have fixed handling of quotes and shifted the directory parsing code out of `GameListBuilder` and into a dedicated `MamePathManager` class, along with tests covering what is hopefully all permutations of valid path strings. I have also added logging for all of these parsing failures.

(apologies for the bogus branch name)

### CODE REVIEW

**Comment by mika76** [comment]
I wonder - is there ever any chance for multiple quoted items to be in the same string? If so I'm not sure your regex will work...

ie: `"c:\mame\roms";"c:\mame2\roms (old)"`

**Comment by mika76** [comment]
Also, I might have missed it, the unit tests are not taking absolute paths into consideration...

**Comment by nullpainter** [comment]
> I wonder - is there ever any chance for multiple quoted items to be in the same string? If so I'm not sure your regex will work

The `-showconfig` command reformats paths - can you check to see what it does with this?

**Comment by mika76** [comment]
sure will do

**Comment by nullpainter** [comment]
> Also, I might have missed it, the unit tests are not taking absolute paths into consideration...

Not at computer right now, but I have several tests dealing with absolute paths...

**Comment by nullpainter** [comment]
> I wonder - is there ever any chance for multiple quoted items to be in the same string? If so I'm not sure your regex will work...

You're right - however it's not just my regex which is at fault!

For the following `rompath` in `mame.ini`:

```
rompath                   "roms\vector";"C:\code\tools\mame\roms\shmups"
````

MAME reports the path as:

```
$ ./mame64 -showconfig | grep rompath
rompath                   roms\vector";"C:\code\tools\mame\roms\shmups
```

As you can probably guess from this - this is just a bogus rom path so probably not something we need to worry about as MAME will never be able to get the game statuses or play the games anyway.

**Comment by mika76** [comment]
Great stuff - it seems mame does things weirdly itself 😄

**Comment by nullpainter** [comment]
Garbage in, garbage out 😄

**Pull request merged**
