### PR TITLE
Game filtering

### PR DESCRIPTION
**Pull request by nullpainter**
This PR is primarily to assist with game management for users without curated sets of ROMs.

Primary changes are:

* Filters out mechanical games
* Adds better checks for BIOS ROMs and runnable games
* Rewrote config form to use WPF
* Added per-column subtractive game filtering
* Added global all/selected games filter
* Added game category and subcategory to game list via bundled `catver.ini`
* Added rotation to game list
* Added number of selected games to label
* Migrated off legacy `packages.config` to PackageReferences
* Replaced troublesome ILMerge with ILRepack
* Small fixes
* Shuffled options to better make use of space

Due to the number of moving parts with game filtering, this should be considered a beta release and tested accordingly. 

**Edit**: options shuffled, screenshots updated. ~~I haven't updated the screenshots in the documentation as I'm not sure what your feeling is about the current tab contents - I've had to make everything quite a bit larger to accommodate the additional game list columns, but this is making all of the other tabs larger than is warranted for what's on them.~~

**Edit**: all filtering rewritten. ~~There's more code in some of the code behind than I would like, which is resulting in unnecessarily complexity, compromises and confusing chat between the code behind and view models. This is largely to work around the `DataGridExtensions` package which I am using for the filtering. Since I have bypassed most of the library already, I will tidy this up shortly and reimplement what's missing.~~

Note that ILRepack integration has been shifted to a new `Repack` build target. This allows integration tests to work against debug and release builds. The version of the distributed screensaver must be built from the `Repack` target. This may require building twice - one for tests, and another for distribution.

image

### CODE REVIEW

**Comment by mika76** [comment]
Hey @nullpainter thanks for the update - I'll have a look as soon as I can. Do you think we should update the version number? Maybe 3.0 considering the UI rewrite?

**Comment by nullpainter** [comment]
>  Maybe 3.0 considering the UI rewrite?

You asked this last time and I was reluctant, but there _has_ been quite a few changes and the filtering does add a significant amount more flexibility (I'm biased but I'm loving it) so would be happy with 3.0 if you are 😄

**Comment by mika76** [comment]
Yeah I think it's pretty warranted... 👍 💯

**Comment by mika76** [comment]
Hey @nullpainter do we need more than the .scr file now? I tried it but nothing happens. Doesn't run screensaver nor config form. Only got the scr though...

**Comment by nullpainter** [comment]
Hi @mika76, how were you building it? I noted briefly in an update to this PR's description, but there's a new build target called `Repack`. This target creates the target, combined `.scr` file which is required for distribution.

This is because the integration tests don't work easily against an ILRepack'd build. So, if it's straightforward, you will need to change the build process to perform a release build, running tests (as currently), then a separate build using the `Repack` target. This will result in a `bin\Repack` directory, containing only the `.exe` and `.scr`.

**Comment by mika76** [comment]
I was using the appveryor artifacts. I'll try and change the build and let you know, otherwise we should probably move over to a yml file...

**Comment by nullpainter** [comment]
Not a bad idea if we want decentralised management of the build process.

**Comment by mika76** [comment]
Hey @nullpainter sorry I didn't test till now. After adding the repack configuration I got the proper exe and managed to get it working. Overall it works great and looks great. 


Some comments:
1. Can  you make the form re-sizable? Seems it's currently locked to one size.
2. Could it maybe do a rebuild list the first time you run it - this should then update the previous versions xml file. When I opened it I tried filtering a bit and it was buggy and then I clicked clear filter and the window closed. I realised it's probably because things are missing from the xml file, so after doing a Rebuild list all functions work fine.
3. Rebuilding list kinda looked like it was frozen for a while until the progress bar suddenly updated after a while. Any way to show it's working while it's busy? I think the progress bar has some property for that.
4. Currently the `Rebuild` config creates the msi, but it should probably be the `repack` one and I think the `.exe` needs to be renamed to `.scr` (this might be done by the installer itself - I forgot to check)
5. I wonder if you need the apply button? All filtering and other actions work immediately when selecting, only the `show all` and `show selected` option required the apply.

Overall I think this is amazing - the filtering looks and works great.

**Comment by mika76** [comment]
Just had a weird issue - mamesaver.scr config and run work fine when running off my desktop - but when I move the file to the System32 folder then trying to config or run causes some weird .net exception...

**Comment by mika76** [comment]
You mean 32 bit? (syswow64 is for 32 bit programs running on 64 bit OS) Does `Any CPU` not work in our case? I guess if not 32 bit is the best option since it should work on all machines then...

**Comment by mika76** [comment]
Confirmed - works fine in syswow64 folder. I guess this is ok, as long as the installer knows where to put it.

**Comment by nullpainter** [comment]
In this branch, I've just squashed two related bugs which caused unhandled failures (and no stack trace!) when any invocation of MAME hadn't terminated before the screensaver quit.

**Pull request merged**
