### PR TITLE
Detect best primary monitor for running mame

### PR DESCRIPTION
**Pull request by andyvans**
1. Instead of using the primary monitor for MAME, detect the best monitor to run MAME on by picking the monitor with the greatest Y axis.  This is because MAME games are usually 4x3 or 3x4, but screens are largely 16x9.
2. Remove an unused function in CaptureScreen.

### CODE REVIEW

**Comment by mika76** [comment]
Awesome man, I'll try it out this morning...

**Comment by mika76** [comment]
Hey @andyvans - The mame game works like a bomb 💣 - but the splash screen is still not stretching...

**Comment by andyvans** [comment]
Hey @mika76 what resolutions are your monitors? 

All the details should be in log file in %temp%\mamesaver\logs.  I suspect I need to grab the right amount of the source/destination Rect when they have different ratios.

**Comment by nullpainter** [comment]
It's not anything silly to do with a high DPI display, is it @andyvans? That logo isn't even centred...

**Comment by mika76** [comment]
I can try a debug it maybe tomorrow if I have time in case you still can't re-create...

**Comment by andyvans** [comment]
Hi @mika76. I think I have a solution. It is related to the high dpi screen you have. Windows tells lies to non-highdpi aware applications.  That is why the screen is small.

**Comment by mika76** [comment]
Hey @andyvans thanks - I'll give it a try as soon as I can...

**Comment by mika76** [comment]
Just tried the last commit - same result - not covering the whole screen...

**Comment by andyvans** [comment]
Ok. Thanks. I will have a go with a high dpi screen in the weekend.

**Comment by mika76** [comment]
I cloned your repo so will try debug myself and see if I can help out - only thing is I'm kinda busy today and travelling tonight so might only get to it over the weekend. Will keep you posted...

**Comment by mika76** [comment]
I managed to have a quick look and I think I might know what is causing the issue (config wise not code wise)

I have a laptop to which I've connected a screen. The external screen is set to the Main Display and is the one that I drop the resolution of to 1600x or 1400x. If I change the Main Display to be the laptop (larger res) screen then all works fine.

I assume there is some issue in CaptureScreen and what handle it's getting for the DesktopWindow maybe?

**Comment by mika76** [comment]
This might come in useful: https://stackoverflow.com/questions/28261311/multiple-screen-capture-with-msdn-library

**Comment by mika76** [comment]
I just can't seem to figure it out - but an interesting anecodote is that if I change the `BackgroundForm.FormBorderStyle` from `None` to something else like `Sizeable` then it seems to fill the screen (albeit with the border which looks crap)

**Comment by mika76** [comment]
So setting the border to it's normal `Sizeable` and then using SetWindowLong to a compatible style seems to get us most of the way - I just have not been able to get rid of the caption AND the border...

**Comment by mika76** [comment]
Hey @andyvans I merged #22 but I see this has now caused a conflict - sorry about that - I was trying to get to the bottom of the small window mystery and thought I'd merge after that but now I've caused a problem. Would you mind updating?

**Comment by mika76** [comment]
The most interesting of article so far about this issue: https://stackoverflow.com/questions/22874211/setwindowpos-and-multiple-monitors-with-different-resolutions

**Comment by andyvans** [comment]
@mika76 done.  I had a go the in weekend, but still cannot reproduce the issue. I think it is because the only high dpi monitor I have is only my laptop.

**Comment by andyvans** [comment]
And I just fixed the logging of the dpi details. It now shows

`2018-09-03 09:53:04.531 +12:00 [INF] Blank screen resized \\.\DISPLAY2 {X=-1920,Y=0,Width=1920,Height=1080} xDpi 96 yDpi 96
2018-09-03 09:53:04.550 +12:00 [INF] Blank screen resized \\.\DISPLAY1 {X=0,Y=0,Width=1920,Height=1080} xDpi 96 yDpi 96`

**Comment by andyvans** [comment]
>Basically I have a laptop 1920x1080 and a screen (same res) - I change the screen to 1440x900 and then try 
@mika76 do you only see the problem when running screens at non-native resolutions? Was this because you enjoy 1440x900 🤢 or you were testing the cloning at different resolutions?

**Comment by nullpainter** [comment]
Also, was the issue still present after rebooting / logging off? I've been able to replicate it, but haven't investigated yet if it is a persistent or temporary issue.

**Comment by andyvans** [comment]
@mika76 Give the latest a go (commit id 80255c6).  While you may see some temporary window resizing, I think it sorts itself out now and runs in full screen.

**Comment by mika76** [comment]
Hey @andyvans unfortunately the last commit didn't do anything different. But I think I figured it out...

```patch
diff --git a/Mamesaver/BackgroundForm.Designer.cs b/Mamesaver/BackgroundForm.Designer.cs
index 5b32aad..e3f0de5 100644
--- a/Mamesaver/BackgroundForm.Designer.cs
+++ b/Mamesaver/BackgroundForm.Designer.cs
@@ -103,9 +103,7 @@ namespace Mamesaver
             this.ShowIcon = false;
             this.ShowInTaskbar = false;
             this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
-            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
             this.TopMost = true;
-            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
             ((System.ComponentModel.ISupportInitialize)(this.mameLogo)).EndInit();
             this.ResumeLayout(false);
 

```

It seems by removing the `FormWindowState.Maximized` it solved the issue - I removed the startup position as well since SetWindowPos does the work for you.

**Comment by andyvans** [comment]
Cool.  Good spotting. I had added that change to my branch

**Comment by mika76** [comment]
Fantastic - Mamesaver is looking and working so nice now 😄

**Pull request merged**
