### PR TITLE
Feature/game filtering

### PR DESCRIPTION
**Pull request by nullpainter**
Filters out mechanical games, adds better check for BIOS ROMs and runnable games.

### CODE REVIEW

**Comment by mika76** [comment]
Hahaha 109 files changed - I think your comment might be a tad un-representative 😆

**Comment by mika76** [comment]
Hmm tried running the appveyor build bit it just give me the waiting cursor for a second and then nothing happens. No errors, logs, nothing...

**Comment by nullpainter** [comment]
> Oh goodness, I forgot this PR was on that branch. It's definitely not ready yet. How about I close this and re-open when it's all done?

**Comment by mika76** [comment]
ah ok no prob

**Comment by nullpainter** [comment]
(it was a "hmm, I've changed a _lot_ of stuff and it's all just on my laptop" push...)

**Pull request closed without merging**
